### PR TITLE
add auto generration for category-files

### PR DESCRIPTION
**Pull request by tommueller**
this little bash-script can be run while the jekyll is running locally. it will then automatically generate the necessary files in the _categories folder automatically

### CODE REVIEW

**Comment by thomasvaeth** [comment]
I haven't had a time to test this yet. Today or tomorrow!

**Comment by iamsebastian** [comment]
Is it today or tomorrow now, @thomasvaeth? :)

**Comment by thomasvaeth** [comment]
Hah I seriously pulled this weeks/months ago and I couldn't get it to work locally. Feel free to email me at thomas.vaeth@gmail.com if you can help out. I just added Parallax and some more blog styles this weekend because I made it a Ghost theme also.

**Comment by iamsebastian** [comment]
@thomasvaeth 
Will create a new pull request.

**Pull request closed without merging**
